name: Docker Image Scan

on: [push]

env:
  USER: "aiboosts"

jobs:
  trivy_scan:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Login to GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}  # Use the GitHub username (actor)
          password: ${{ secrets.GHCR_TOKEN }}  # Use the secret token

      # Build the Docker image
      - name: Build the hello-docker Docker image
        run: |
          docker build -t ghcr.io/$USER/hello-docker-gcr-demo:latest .

      # Install Trivy (Specific version v0.60.1)
      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.0
        with:
          version: latest # Specify the desired version

      # Scan the Docker image for vulnerabilities
      - name: Scan Docker image for vulnerabilities
        run: |
          trivy image --format json --output trivy_output.json ghcr.io/$USER/hello-docker-gcr-demo:latest
        env:
          TRIVY_SEVERITY: HIGH,CRITICAL  # Optional: Set severity levels to scan for --severity HIGH,CRITICAL --exit-code 1
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan
          path: trivy_output.json
      # Push the Docker image to GitHub Container Registry
      - name: Push the Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/$USER/hello-docker-gcr-demo:latest
